apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          activeDeadLines: 10
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - uname
          restartPolicy: OnFailure