apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: nginx
    image: nginx
    image:  registry/user/image
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  - name: redis
    image: redis
  - name: memcached
    image: memcached
  - name: consul
    image:  consul

  