apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  image: nginx 
  namespace: default
spec:
  volumes: PersistentVolumeClaim 
    name: app-data-claim
    MountPath:
     path:  /usr/share/nginx/html 
  containers:
  - name: nginx