apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMounts:
      - hostPath:
         path: /data/app-data
         touch: index.html 
            vi: "Custom-Index"
        name: mypd
  storageClassName: ssd
  resources:
    requests:
      storage: 1Gi